In [1]:
import numpy as np

In [5]:
my_list = [3,23,1,3]
my_list

[3, 23, 1, 3]

In [6]:
my_matrix = [[3,3,3],[5,5,5],[2,2,2]]
my_matrix

[[3, 3, 3], [5, 5, 5], [2, 2, 2]]

In [7]:
np.array(my_matrix)

array([[3, 3, 3],
       [5, 5, 5],
       [2, 2, 2]])

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,4,3)

array([0., 2., 4.])

In [20]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand(2)

array([0.22702537, 0.17839389])

In [24]:
np.random.randn(5,5)

array([[-0.04534808,  1.10675264,  1.02237513,  0.30952471,  0.26548848],
       [ 0.18554458, -0.95678658, -1.09600068, -1.54158727, -0.14488924],
       [ 1.69203028,  1.09852856,  0.59701358,  0.14947012, -0.00553252],
       [ 0.57459981, -1.49329357,  0.71764422, -1.18784858,  1.78753725],
       [-2.23348009, -0.00556876,  0.89531277,  0.43267161, -0.91081218]])

In [25]:
np.random.randint(1,100,10)

array([87, 11, 86, 10, 64,  8,  4, 96, 96, 43])

In [27]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([ 2, 16,  7, 31, 42, 22, 40,  3, 29, 42])

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ey = np.eye(5,5)

In [32]:
ey

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
arr+ey

ValueError: operands could not be broadcast together with shapes (25,) (5,5) 

In [34]:
ranarr.max()

42

In [35]:
ranarr.min()

2

In [37]:
ranarr.argmin()

0

In [40]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [41]:
arr.dtype

dtype('int64')